name    'gajdaw-phpmyadmin'
version '0.1.9'
source 'git://github.com/pro-vagrant/puppet-phpmyadmin.git'
author ' Włodzimierz Gajda'
license 'MIT'
summary 'The module to install phpmyadmin'
description 'The module to install phpmyadmin'
project_page 'https://github.com/puppet-by-examples/puppet-phpmyadmin'
